PyTorch basics

In [ ]:
import torch

In [3]:
x= torch.tensor([1, 2, 3, 4, 5])
print(x)

tensor([1, 2, 3, 4, 5])


In [4]:
y=torch.rand(5,3)
print(y)

tensor([[0.6177, 0.6605, 0.0547],
        [0.1368, 0.2694, 0.3030],
        [0.3097, 0.5241, 0.6813],
        [0.1202, 0.5017, 0.5737],
        [0.4612, 0.3973, 0.2148]])


In [9]:
print(x.size())
print(y.shape)

torch.Size([5])
torch.Size([5, 3])


In [15]:
print(x.dtype)

torch.int64


In [20]:
b=torch.rand(4,4)
print(b[:,:])
print(b[:,2])

tensor([[0.6087, 0.4406, 0.9206, 0.9186],
        [0.1617, 0.3800, 0.5753, 0.7857],
        [0.0023, 0.2187, 0.2970, 0.1680],
        [0.9113, 0.7686, 0.4653, 0.1278]])
tensor([0.9206, 0.5753, 0.2970, 0.4653])


In [22]:
c=torch.ones(6)
c=c.numpy()
print(c)
print(type(c))

[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [23]:
e= torch.tensor([1, 2, 3])
f=torch.tensor([1, 2, 3])
print(torch.add(e, f))
print(torch.sub(e, f))

tensor([2, 4, 6])
tensor([0, 0, 0])


Auto_grad

In [36]:
x=torch.rand(5,requires_grad=True)
y=x+4
print(y)
print(y.grad_fn)
z=y*y*2
print(z)
z=z.mean()
print(z)

#Backward
z.backward()
print(x.grad)


tensor([4.4238, 4.7643, 4.3329, 4.7284, 4.7426], grad_fn=<AddBackward0>)
tensor([39.1399, 45.3965, 37.5481, 44.7159, 44.9854], grad_fn=<MulBackward0>)
tensor(42.3572, grad_fn=<MeanBackward0>)
tensor([3.5390, 3.8114, 3.4663, 3.7827, 3.7941])


Image to Tensor

In [2]:
import cv2
from torchvision.transforms import transforms


img=cv2.imread('/home/endoai/Desktop/intern task/sample.jpeg')
img=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

transform = transforms.Compose([transforms.ToTensor()])
img_tensor = transform(img)
print(img_tensor)

tensor([[[0.8157, 0.8196, 0.8235,  ..., 0.3804, 0.3843, 0.3922],
         [0.8157, 0.8196, 0.8235,  ..., 0.4000, 0.4000, 0.4039],
         [0.8157, 0.8157, 0.8196,  ..., 0.4275, 0.4235, 0.4235],
         ...,
         [0.0275, 0.0627, 0.0745,  ..., 0.1020, 0.1020, 0.0980],
         [0.0235, 0.0431, 0.0627,  ..., 0.1020, 0.1020, 0.1020],
         [0.0275, 0.0353, 0.0588,  ..., 0.1059, 0.1059, 0.1020]]])


uint8 to float32

In [13]:
import numpy as np
import torch

a=np.array([1,2,3,4,5,6],dtype=np.uint8)
a_u = torch.from_numpy(a)
print(a_u)   
print(a_u.dtype)

a_f = a_u.to(torch.float32)
print(a_f)
print(a_f.dtype)


tensor([1, 2, 3, 4, 5, 6], dtype=torch.uint8)
torch.uint8
tensor([1., 2., 3., 4., 5., 6.])
torch.float32


In [9]:
import torch

x = torch.tensor([1, 2,3,4])
y = torch.tensor([10, 20,30])


X, Y = torch.meshgrid(x, y)
print(X)
print(Y)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor([[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]])
